# Generated by Django 6.0.2 on 2026-03-15 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_conversation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('dinner', 'Dinner'), ('custom', 'Custom')], max_length=20)),
                ('meal_name', models.CharField(blank=True, help_text='Custom meal name or auto-filled from recipe', max_length=200)),
                ('calories', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('fats', models.FloatField(default=0)),
                ('servings', models.FloatField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(blank=True, help_text='Recipe this meal was logged from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_logs', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to='recipes.userprofile')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='recipes_mea_user_id_7746f7_idx')],
            },
        ),
    ]
