# Generated by Django 6.0.2 on 2026-03-26 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_ratings_count_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('liked', 'liked'), ('saved', 'saved'), ('commented', 'commented'), ('rated', 'rated'), ('created', 'created'), ('followed', 'followed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities_received', to='recipes.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_generated', to='recipes.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='recipes_act_user_id_d2f91a_idx')],
            },
        ),
    ]
