# Generated by Django 6.0.2 on 2026-03-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborative_boards', to='recipes.userprofile'),
        ),
    ]
