# Generated by Django 6.0.2 on 2026-03-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_complete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='likes_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='saves_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
