# Generated by Django 6.0.2 on 2026-03-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_is_complete_alter_recipe_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='is_ai_estimated',
            field=models.BooleanField(default=False, help_text='Nutrition was auto-estimated by AI'),
        ),
    ]
